version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    working_directory: /opt/rapidus

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            apt-get update
            apt-get install -y curl
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          docker build -t rapidus -f Dockerfile_cov .
          docker run --security-opt seccomp=unconfined rapidus bash run_kcov.sh $CODECOV_TOKEN
